/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dictonary;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JScrollPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author setthi
 */
public class J1 extends javax.swing.JFrame {

    Connection connection;
    String url = "jdbc:mysql://localhost:3306/dictionary";
    String user = "root";
    String pass = "02062004@Se01";

    DefaultListModel<String> inputListModel;
    DefaultListModel<String> outputListModel;
    Statement statement;
    ResultSet resultSet;
    int selectedIndex;
    String selectedItem;
    String translate = "";
    PreparedStatement preparedStatement;

    /**
     * Creates new form J1
     */
    public J1() {
        initComponents();
        listShow();

    }

    // show all word when the application start up 
    private void listShow() {
        inputListModel = new DefaultListModel<>();

        try {

            Class.forName("com.mysql.cj.jdbc.Driver");
            System.out.print("Connected");
            connection = DriverManager.getConnection(url, user, pass);
            //JOptionPane.showMessageDialog(rootPane, "Connected");
            String query = "Select Word from tbdictionary order by Word";
            statement = connection.createStatement();
            resultSet = statement.executeQuery(query);

            while (resultSet.next()) {

                String ss = resultSet.getString(1);

                inputListModel.addElement(ss);

            }

            wordList.setModel(inputListModel);

        } catch (Exception ex) {
            Logger.getLogger(J1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuOption = new javax.swing.JPopupMenu();
        save = new javax.swing.JMenuItem();
        MainPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnHistory = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        wordList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();

        MenuOption.setComponentPopupMenu(MenuOption);

        save.setText("save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        MenuOption.add(save);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("វចនានុក្រមខ្មែរអង់គ្លេស");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setLocation(new java.awt.Point(0, 0));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setName(""); // NOI18N
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Khmer OS Muol Light", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("វចនាអុក្រមអង់គ្លេស-ខ្មែរ");

        btnHistory.setBackground(new java.awt.Color(205, 242, 242));
        btnHistory.setFont(new java.awt.Font("!Khmer OS Siemreap", 0, 12)); // NOI18N
        btnHistory.setText("ប្រវត្តិ");
        btnHistory.setBorder(null);
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(204, 255, 255));
        btnSave.setFont(new java.awt.Font("!Khmer OS Siemreap", 0, 12)); // NOI18N
        btnSave.setText("រក្សាទុក");
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Khmer OS Muol Light", 0, 12)); // NOI18N
        jButton4.setText("បញ្ចូលពាក្យ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("!Khmer OS Siemreap", 0, 12)); // NOI18N
        jLabel1.setText("ពាក្យទាំងអស់");

        searchTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchTextField.setToolTipText("");
        searchTextField.setAutoscrolls(false);
        searchTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        searchTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        searchTextField.setName("វាយបញ្ចូលពាក្យស្វែងរក"); // NOI18N
        searchTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchTextFieldFocusGained(evt);
            }
        });
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("!Khmer OS Siemreap", 1, 14)); // NOI18N
        jLabel2.setText(" ស្វែងរក");

        wordList.setComponentPopupMenu(MenuOption);
        wordList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                wordListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(wordList);

        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout MainPaneLayout = new javax.swing.GroupLayout(MainPane);
        MainPane.setLayout(MainPaneLayout);
        MainPaneLayout.setHorizontalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPaneLayout.createSequentialGroup()
                .addGroup(MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPaneLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPaneLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainPaneLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MainPaneLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jButton4))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        MainPaneLayout.setVerticalGroup(
            MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(MainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        searchTextField.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPane, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        historyForm history = new historyForm();
        history.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SaveJfram save = new SaveJfram();
        save.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnSaveActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        boolean istrue = true;
        String password = "sela";

        do {
            String resultInput = JOptionPane.showInputDialog(this, "Input password");

            if (resultInput != null && resultInput.equals(password)) {
                InputWord inputword = new InputWord();
                inputword.setVisible(true);
                this.dispose();  // Close the main frame
                istrue = false;  // Exit the loop
            } else {
                int resultInt = JOptionPane.showConfirmDialog(rootPane, "Password is incorrect! Try again?", "Oop!", JOptionPane.YES_NO_OPTION);
                if (resultInt == JOptionPane.NO_OPTION) {
                    istrue = false;  // Exit the loop
                } else if (resultInt == JOptionPane.YES_OPTION) {
                    istrue = true;  // Continue the loop
                } else {
                    istrue = false;  // Handle other cases, like if the dialog is closed
                }
            }
        } while (istrue);

        //this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void wordListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_wordListValueChanged
        // TODO add your handling code here:
        outputListModel = new DefaultListModel<>();
        if (!evt.getValueIsAdjusting()) {
            outputListModel.clear();
            // Get the selected index
            selectedIndex = wordList.getSelectedIndex();

            // Get the selected item
            if (selectedIndex != -1) {
                selectedItem = wordList.getModel().getElementAt(selectedIndex);
                // Update the JLabel with the selected item
                String query = "Select Translate from tbdictionary where Word= ?";

                try {
                    preparedStatement = connection.prepareStatement(query);
                    preparedStatement.setString(1, selectedItem);
                    resultSet = preparedStatement.executeQuery();

                    while (resultSet.next()) {
                        translate = resultSet.getString(1);
                        outputListModel.addElement(translate);
                    }
                    jList2.setModel(outputListModel);

                    System.out.println(selectedItem + "and" + translate);

                    String insertTotbHistory = "INSERT INTO tbhistory(Word,Translate) values(?,?)";
                    preparedStatement = connection.prepareStatement(insertTotbHistory);
                    preparedStatement.setString(1, selectedItem);
                    preparedStatement.setString(2, translate);
                    int inserted = preparedStatement.executeUpdate();
                    preparedStatement.close();
                    if (inserted > 0) {
                        System.out.println("success");
                    } else {
                        System.out.println("fail");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(J1.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        }  // TOD

    }//GEN-LAST:event_wordListValueChanged

    private void searchTextFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchTextFieldFocusGained
        // TODO add your handling code here:
        searchTextField.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filterList();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filterList();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filterList();
            }

            private void filterList() {
                String filter = searchTextField.getText().toLowerCase();

                DefaultListModel<String> filterListModel = new DefaultListModel<>();
                for (int i = 0; i < inputListModel.getSize(); i++) {
                    String word = inputListModel.getElementAt(i);
                    if (word.toLowerCase().contains(filter)) {
                        filterListModel.addElement(word);
                    }
                }
                wordList.setModel(filterListModel);
            }

        });
    }//GEN-LAST:event_searchTextFieldFocusGained

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        selectedIndex = wordList.getSelectedIndex();
        // Get the selected item
        if (selectedIndex != -1) {
            selectedItem = wordList.getModel().getElementAt(selectedIndex);
            System.out.println(selectedItem);
            System.out.println(translate);

            String query = "INSERT INTO tbsave(Word,Translate)values(?,?)";
            try {
                connection = DriverManager.getConnection(url, user, pass);
                preparedStatement = connection.prepareStatement(query);
                preparedStatement.setString(1, selectedItem);
                preparedStatement.setString(2, translate);
                int result = preparedStatement.executeUpdate();
                if (result > 0) {
                    System.out.println("done!");
                    preparedStatement.close();
                    connection.close();
                }

            } catch (SQLException ex) {
                Logger.getLogger(J1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(J1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(J1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(J1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(J1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new J1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPane;
    private javax.swing.JPopupMenu MenuOption;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem save;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JList<String> wordList;
    // End of variables declaration//GEN-END:variables
}
